version: "2"
services:
  redis:
    image: redis:4
    command: redis-server
    container_name: redis
    ports:
      - '6379:6379'
    environment:
      - REDIS_HOST=redis
    networks:
      - repo_default


networks:
  repo_default:
    external: true  

